version: '3.4'

services:
  catalogdb:
    image: mongo
  
  basketdb:
    image: redis:alpine #alpine is a light weight version which takes less space

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

volumes: #to keep and save some data in case image is changed ot deleted or whatever tha data is not  lost,in this case to keep our data on mongodb safe
  mongo_data: 
